### ISSUE TITLE
r-ggplot render in latest update. 

### ISSUE THREAD

**Issue by IanSudbery** [AndreasHeger/CGATReport#36]
```
[ians@cgath2 project_pipeline_iCLIP5]$ cgatreport-test --path=../src/pipeline_docs/pipeline_proj028/trackers/ -t ChimericReadProportions -r r-ggplot --o statement='aes(protein, fraction, col=replicate, ymin=fraction-1.96*se, ymax=fraction+1.96*se) + geom_bar(position="dodge", stat="identity") + theme_bw()' --o groupby=all
/ifs/apps/apps/python-2.7.11-gcc-5.2.1/lib/python2.7/site-packages/rpy2/robjects/functions.py:106: UserWarning: Find out what's changed in ggplot2 at
http://github.com/tidyverse/ggplot2/releases.

  res = super(Function, self).__call__(*new_args, **new_kwargs)
WARNING:root:could not find module ChimericReadProportions in None: msg=No module named ChimericReadProportions
.. ---- TEMPLATE START --------

.. report:: ChimericReads.ChimericReadProportions
   :render: r-ggplot
   :groupby: all
   :statement: aes(protein, fraction, col=replicate, ymin=fraction-1.96*se, ymax=fraction+1.96*se) + geom_bar(position="dodge", stat="identity") + theme_bw()

   add caption here

.. ---- TEMPLATE END ----------

.. ---- OUTPUT-----------------
b''
b''
b''
b''
b'#$ggplot $#'
b''
b''
Traceback (most recent call last):
  File "/ifs/devel/Ian/python/bin/cgatreport-test", line 9, in <module>
    load_entry_point('CGATReport', 'console_scripts', 'cgatreport-test')()
  File "/ifs/devel/Ian/python/lib/python2.7/site-packages/CGATReport-0.7.6-py2.7.egg/CGATReport/test.py", line 590, in main
    for r in rr:
TypeError: 'ResultBlock' object is not iterable
```

**Comment by AndreasHeger** [comment]
Thanks, will take a look at this today.

**Comment by AndreasHeger** [comment]
Fixed. It should now work now. Note trackers need the full modulename.classname specification now:
```
cgatreport-test --path=../src/pipeline_docs/pipeline_proj028/trackers/ -t ChimericReads.ChimericReadProportions ...
```
